version: '3.8'

services:
  web:
    image: NAMEOFIMAGE
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=XXX.postgres.database.azure.com;Database=DB;Port=5432;User Id=USER;Password=PASSWORD;Ssl Mode=Require;Trust Server Certificate=true
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - "5432:5432"
